### ISSUE TITLE
How to adjust the size of icon? 

### ISSUE THREAD

**Issue by lanistor** [sanket-vekariya/flutter_flexible_toast#3] opened 2020-02-23 13:03 UTC
How to adjust the size of icon?  It's a little big in iOS.

This's really a good library, don't rely on BuildContext, so we can use it anywhere. Thanks a lot.

**Comment by iosparesh** [comment] 2020-02-25 06:32
> How to adjust the size of icon? It's a little big in iOS.
> 
> This's really a good library, don't rely on BuildContext, so we can use it anywhere. Thanks a lot.

Thanks that you like this plug-in,
Image size adjustment will be available in the next release.

**Comment by sanket-vekariya** [comment] 2020-02-25 08:39
New Update:
We have added an optional "imageSize" parameter for controlling the leading image size now.
The issue is solved now and marking as "close".

**Closed as completed by sanket-vekariya** 2020-02-25 08:39 UTC
